# Generated by Django 3.2.3 on 2021-06-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20210609_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('flights', models.ManyToManyField(related_name='passengers', to='airline.flight')),
            ],
        ),
    ]
